name: Distribute to App Store Connect

permissions:
    contents: write 

on:
    push:
        branches:
            - 'release/**'
            - 'main/**'

jobs:
    distribute:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v4
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.1'
        - run: bundle exec fastlane distribute
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
