name: Distribute to App Store Connect

permissions:
  contents: write 

on:
  push:
    branches:
      - 'release/**'
      - 'beta/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # or your required version

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Run Fastlane
        run: bundle exec fastlane distribute
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          MATCH_GIT_BASIC_AUTHORIZATION: "Basic ${{ secrets.GH_TOKEN }}"
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Added for GitHub authentication
          
